### PR TITLE
ffmpeg: fix build regression

### LINKED ISSUE #373: compilation error with --feature=video-prebuilt-static due to fps change
error:

```rs
error[E0369]: cannot divide `Option<f32>` by `f32`
  --> src\bin\ffmpeg_source.rs:34:35
   |
34 |         let filter_fps = rate.fps / rate.speed;
   |                          -------- ^ ---------- f32
   |                          |
   |                          Option<f32>
   |
note: `Option<f32>` does not implement `Div<f32>`
  --> D:\W\B\src\rustc-1.93.1-src\library\core\src\option.rs:600:1
   |
   = note: `Option<f32>` is defined in another crate

error[E0369]: cannot divide `Option<f32>` by `f32`
  --> src\bin\ffmpeg_source.rs:44:44
   |
44 |             let filter_fps = self.rate.fps / self.rate.speed;
   |                              ------------- ^ --------------- f32
   |                              |
   |                              Option<f32>
   |
note: `Option<f32>` does not implement `Div<f32>`
  --> D:\W\B\src\rustc-1.93.1-src\library\core\src\option.rs:600:1
   |
   = note: `Option<f32>` is defined in another crate

error[E0605]: non-primitive cast: `Option<f32>` as `f64`
  --> src\bin\ffmpeg_source.rs:91:36
   |
91 |         let pts_frame_step = 1.0 / self.rate.fps as f64;
   |                                    ^^^^^^^^^^^^^^^^^^^^ an `as` expression can be used to convert enum types to numeric types only if the enum type is unit-only or field-less
   |
   = note: see https://doc.rust-lang.org/reference/items/enumerations.html#casting for more information
```

Seems to be caused by https://github.com/ImageOptim/gifski/pull/362

### PR DESCRIPTION
**Pull request by anisse**
ffmpeg handling code is not built by default, so it felt through the cracks of the conversion of fps to an Option.

Fixes #373

### CODE REVIEW

**Comment by kornelski** [comment]
Thank you
