### ISSUE TITLE
Build failure on Windows during "Compiling winapi v0.3.6"

### ISSUE THREAD

**Issue by NickeManarin** [ImageOptim/gifski#68]
After downloading the latest release of Rust, the latest version of this project, and running `cargo build --release`, I got some errors when building `lodepng`.

I tried running `cargo update` and building it again, now I'm getting this:

```
PS C:\Users\nicke\Projects\gifski> cargo build --release  
warning: unused manifest key: package.autobins  
 Downloading rayon v1.0.3  
 Downloading lodepng v2.4.2  
 Downloading gif v0.10.1  
 Downloading wild v2.0.1  
 Downloading imagequant-sys v2.12.2  
 Downloading libc v0.2.46
 Downloading cc v1.0.28
 Downloading cfg-if v0.1.6
 Downloading nodrop v0.1.13
 Downloading arrayvec v0.4.10
 Downloading lazy_static v1.2.0
 Downloading num_cpus v1.9.0
 Downloading backtrace v0.3.13
 Downloading rustc-demangle v0.1.13
 Downloading autocfg v0.1.1
 Downloading time v0.1.42
 Downloading winapi v0.3.6
   Compiling nodrop v0.1.13
   Compiling arrayvec v0.4.10
   Compiling autocfg v0.1.1
   Compiling libc v0.2.46
   Compiling cfg-if v0.1.6
   Compiling rustc-demangle v0.1.13
   Compiling cc v1.0.28
   Compiling winapi v0.3.6
error[E0599]: no method named 'filter' found for type 'std::option::Option<std::path::PathBuf>' in the current scope
    Compiling-->  C:\Users\nicke\.cargo\registry\src\github.com-1ecc6299db9ec823\cc-1.0.28\src\windows_registry.rs:266:18lazy_static
 v    1.|2
.2660
|                 .filter(|ref path| path.is_file());
    |                  ^^^^^^
error: '<core::cell::Cell<T>>::new' is not yet stable as a const fn
  --> C:\Users\nicke\.cargo\registry\src\github.com-1ecc6299db9ec823\lazy_static-1.2.0\src\inline_lazy.rs:20:33
   |
20 |     pub const INIT: Self = Lazy(Cell::new(None), ONCE_INIT);
   |                                 ^^^^^^^^^^^^^^^
    |
   |
    = note: the method 'filter' exists but the following trait bounds were not satisfied:
            '&mut std::option::Option<std::path::PathBuf> : std::iter::Iterator'
   = help: in Nightly builds, add '#![feature(const_cell_new)]' to the crate attributes to enable

= help: did you mean 'iter'?

error: aborting due to previous error

error[E0599]error:: no method named 'trim_start_matches' found for type '&str' in the current scope
Could not compile 'lazy_static'.
--> warning:C:\Users\nicke\.cargo\registry\src\github.com-1ecc6299db9ec823\cc-1.0.28\src\windows_registry.rs:640:33
    build failed, waiting for other jobs to finish...
|
640 |                 .and_then(|s| s.trim_start_matches("v").replace(".", "").parse().ok());
    |                                 ^^^^^^^^^^^^^^^^^^
    |
    = help: did you mean 'trim_left_matches'?

error: aborting due to 2 previous errors

error: Could not compile 'cc'.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Aditional info:
**cargo --version**
`cargo 0.23.0 (61fa02415 2017-11-22)`
**rustc --version**
`rustc 1.22.1 (05e2e1c41 2017-11-22)`

While building before running `cargo update`, it was possible to build with `winapi v0.3.5`, but of course, it was failing with `lodepng`.

**Comment by kornelski** [comment]
Rust 1.30 is required.

Basically with Rust you always have to have the very latest version of the compiler. The ecosystem doesn't care about compilers that are more than 6 weeks old.

**Comment by NickeManarin** [comment]
Strange, the installer for windows ([downloaded from here](https://www.rust-lang.org/tools/install)) installs 1.22.1, but by running `rustup update` it reaches 1.31.1 

Anyway, thanks! It's compiling again normally. :)
