### PR TITLE
Support ffmpeg 5.x and 6.x

### LINKED ISSUE #242: Not compatible with ffmpeg 5
On ArchLinux, with `cargo install gifski --features=video`, rustc complains the following
```
error[E0599]: no method named `codec` found for struct `Stream` in the current scope
  --> /home/sb/.cargo/registry/src/github.com-1ecc6299db9ec823/gifski-1.6.6/src/bin/ffmpeg_source.rs:48:34
   |
48 |             let decoder = stream.codec().decoder().video().map_err(|e| format!("Unable to decode the codec used in the video: {}", e))?;
   |                                  ^^^^^ method not found in `Stream<'_>`

For more information about this error, try `rustc --explain E0599`.
error: failed to compile `gifski v1.6.6`, intermediate artifacts can be found at `/tmp/cargo-installuQxfHf`

Caused by:
  could not compile `gifski` due to previous error
```
But apparently that method [does exist](https://docs.rs/ffmpeg/0.3.0/ffmpeg/struct.Stream.html#method.codec).

### PR DESCRIPTION
**Pull request by pekkarr**
Adds support for ffmpeg 5.x and 6.x (fixes #242).

The code has been tested with both ffmpeg 4.4 and 6.0 on Arch Linux. It should work with 5.0 too since the same APIs are available but I haven't tested that.

The [forked `ffmpeg-sys-next`](../blob/1.10.3/Cargo.toml#L91) with cross-compilation fixes has version 4.4.0 of `ffmpeg-sys-next`, so it can't be used until the fork is updated to a newer version. Cargo will emit a warning and ignore the fork when building with newer ffmpeg.

### CODE REVIEW

**Comment by kornelski** [comment]
That's great. Thank you!

**Comment by pekkarr** [comment]
Could you also update `Cargo.lock` with the new ffmpeg? I didn't include that in the pr.
